### ISSUE TITLE
"Instruction requires : Not 64-bit mode" error on iPhone 5s simulator.

### ISSUE THREAD

**Issue by eshwartm** [mdejong/AVAnimator#13]
In CpuArch.c, 
**asm** **volatile**("pushl %%ebx      \n\t" /\* save %ebx _/
              "cpuid            \n\t"
               "movl %%ebx, %1   \n\t" /_ save what cpuid just put in %ebx _/
               "popl %%ebx       \n\t" /_ restore the old %ebx _/
               : "=a"(_a), "=r"(_b), "=c"(_c), "=d"(*d)
               : "a"(function)
               : "cc");

While executing for iPhone 5s, "Instruction requires : Not 64-bit mode", appears on that line. So I thought the command should be pushq and popq in 64 bit mode. 
Then it says "invalid operand for instruction".

Well since I don't know much asm I thought I shouldn't do anything more and ask about it here right away.

**Comment by Tim9Liu9** [comment]
#if defined(__x86_64__) || defined(_M_AMD64) || defined (_M_X64) || defined (__aarch64__)
    __asm__ __volatile__("pushq %%rbx     \n\t"
                         "cpuid            \n\t"
                         "movl %%ebx, %1   \n\t" /* save what cpuid just put in %ebx */
                         "popq %%rbx \n\t" /* restore the old %ebx */
                         : "=a"(*a), "=r"(*b), "=c"(*c), "=d"(*d)
                         : "a"(function)
                         : "cc");
#else
    
    __asm__ __volatile__("pushl %%ebx      \n\t" /* save %ebx */
                         "cpuid            \n\t"
                         "movl %%ebx, %1   \n\t" /* save what cpuid just put in %ebx */
                         "popl %%ebx       \n\t" /* restore the old %ebx */
                         : "=a"(*a), "=r"(*b), "=c"(*c), "=d"(*d)
                         : "a"(function)
                         : "cc");
#endif

**Comment by yurevich1** [comment]
In my case I've changed
`#if defined(x86_64) || defined(M_AMD64) || defined(MY_CPU_AMD64) || defined (M_X64) || defined (__aarch64)`
to
`#if defined(x86_64) || defined(M_AMD64) || defined (M_X64) || defined (__aarch64)`

because the code in the previous comment had not compiled.

After my changes the code had compiled.
