### ISSUE TITLE
mmap error when building on 64-bit device for iOS 9

### ISSUE THREAD

**Issue by foruse** [mdejong/AVAnimator#19]
Hi there 
same issue appearing again when new iOS 9 came up. Please advice!!
What we did is we updated AVAnimator files the latest version. We've marked 32-bit devices  as 
a valid architecture. It works fine for simulator but whenever we try to run it on iPhone 6, iPad air crash appears
This seems to work fine on 64-bit simulator but crashes right away on device. Note, I am using the mvid format for animations.

Assertion failure in -[SegmentedMappedData mapSegment], .../AVAnimator/SegmentedMappedData.m:330

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'mmap result EINVAL'

**Comment by mdejong** [comment]
I just tested both the StreetFighter and the KittyBoom example on iOS 9.0.1 on a 64 bit iPad and it seems to be working properly. The most likely issue is that you might not be using the most up to date version of the AVAnimator code from github. To run properly on 64 bit devices you have to use the HEAD of https://github.com/mdejong/AVAnimator and https://github.com/mdejong/MvidMovieMaker (if you are creating .mvid files).

**Comment by mdejong** [comment]
Could you update the github version of the source code and try this again? I would like to learn if this problem is still showing up and why.

**Comment by mdejong** [comment]
This problem has been addressed, closing.
