### ISSUE TITLE
Cocoapods 2014 since last update

### ISSUE THREAD

**Issue by viktorgardart** [mdejong/AVAnimator#20]
Any reason the [pod](https://cocoapods.org/pods/AVAnimator) haven't been updated since 2014?

**Comment by mdejong** [comment]
I just submitted a ticket to get AVAnimator removed from the list of CocoaPods libs. https://github.com/CocoaPods/CocoaPods/issues/4970

**Comment by mdejong** [comment]
Confirmed that out of date cocoapod is not longer online. Closing.

**Comment by viktorgardart** [comment]
Thank you! 

Is there a reason _why_ you don't want it at cocoapods?

**Comment by mdejong** [comment]
Having more than one place where the software is published means things can get out of date. Also, people do not seem to do enough research on the license terms of the software. In addition, examples of actually using the library is more important than the github repo of the library itself and the examples on my webpage are what people should be downloading. The library is the implementation, but people want to know how to actually use the implementation to do things.

**Comment by viktorgardart** [comment]
Fair enough :+1: 

Great job with the lib!
