### ISSUE TITLE
Ability to playback video with transparency in a SceneKit node

### ISSUE THREAD

**Issue by davehakim** [mdejong/AVAnimator#24]
Great project! I was wondering if anyone has created a SceneKit node that uses it to play back a video with transparency ?

**Comment by mdejong** [comment]
There is no specific SceneKit plugin, but you can just adapt this yourself to drive video content into a custom view. Here is an example of driving video data into OpenGL as a texture: http://www.modejong.com/blog/post7_load_opengl_textures_with_alpha_channel_on_ios/index.html
